### ISSUE TITLE
Beautiful!!  One issue so far - seasons not changing

### ISSUE THREAD

**Issue by Oosquai** [RustyMods/Seasonality#1]
I love this new mod so much.  Thank you!  I'm using your default settings, with Current Season = Fall and Season Duration = 5.  From the comment above Current Season, I think seasons should be rotating unless Duration is set to 0.  They're not though.  It's always Fall.  Help please?
One other request - would it be possible to have a config option to not display the season icon at all?  I turned the timer off, but I'd like to just hide the indicator completely.
Love this mod so much!  It's beautiful!  Thank you!

**Comment by RustyMods** [comment]
Aah thank you! Yes I'm working on the counter working properly. Seems the logic for how the server handles it is not working as intended. 

A config for icon can and will be added for next update :)

**Comment by Oosquai** [comment]
Hi Rusty!  Every time I load the game now I pause and appreciate how refreshing Seasonality makes everything look.  This is soooooo beautiful!  I have buffs configured per season for my players to consider, and I'm super excited for their reactions when they see this.  Thank you!
Sadly though, I have more news to report.  I noticed my framerates are tanking with this installed.  I'm running a lot of mods, but just removing Seasonality and restarting makes a difference between 30 fps and 90 fps.  Am I doing anything wrong?  If not, is there more testing I could do to help you?

**Comment by RustyMods** [comment]
have you tried changing your boot.config file ? it might give you a bit more frame rates.

gfx-enable-gfx-jobs=1
gfx-enable-native-gfx-jobs=1

add these two lines at the top of the file.

working on improving performance.
