### ISSUE TITLE
Indoor Yule tree is cowered in snow during winter

### ISSUE THREAD

**Issue by Malvi1697** [RustyMods/Seasonality#10]
Not sure if there's a possibility to do sheltered check on this piece maybe? Beautiful mod btw

![image](https://github.com/RustyMods/Seasonality/assets/129746042/41d21069-e8ea-415f-bfbe-533f754179c4)

**Comment by RustyMods** [comment]
Thank you, unfortunately, the way I currently replace textures won't allow for shelter check. For performance reasons, it changes textures globally.
