### ISSUE TITLE
[Suggestion] - Buildable Seasonal items during the respective Seasons

### ISSUE THREAD

**Issue by Yourname942** [RustyMods/Seasonality#11]
It would be very fun/immersive to be able to build the seasonal-specific items based on the respective Seasonality seasons:

Holiday Tree - Winter
Gift Boxes - Winter
3 Yule Pieces - Winter 
Jackoturnip - Fall
Pointy Hat - Winter?
Maypole - Summer
Midsummer Crown - Summer
etc.

Thank you.

**Comment by RustyMods** [comment]
Download Seasonal Tweaks
I added that functionality there
