### ISSUE TITLE
Season is bugged when changing between worlds that are on different seasons

### ISSUE THREAD

**Issue by TheMythicSock** [RustyMods/Seasonality#15]
Was playing fine, but then switched to a world that was created previously to repair some equipment, since I was starting brand new in the current world. Now both are bugged, and the season timer is messed up. If I exit the game entirely and log back in again, it sets the timer to 11 days. If I then log out of the world and back in, it removes the timer completely, the trees display fall texture, and the ground displays spring textures. Have tried everything short of deleting and reinstalling the mod, even started the game without mods and logged into the world, hoping it was a problem with just the world file but no dice. Will keep fooling with it to see if I can accidentally fix it. If I do, will update. Please let me know if I can supply anything that would help.

![valhiem bug](https://github.com/RustyMods/Seasonality/assets/157019112/0484ef7a-9078-4cec-b759-398aa1aeff55)
![other bugshot](https://github.com/RustyMods/Seasonality/assets/157019112/ac7accf6-abf7-4b65-a2de-2b6bbee759b0)

**Comment by TheMythicSock** [comment]
But wait, there's more! I created a brand new world entirely, logged in and there is no season timer. It is spring though, and the texture matches this time. Same character. 

Additionally, I just tried a brand new world, and a new character too. same result. And before that, I uninstalled the mod, and reinstalled it. I've somehow managed to completely break the mod, not sure how. The only mods I have are the BepInEx mod, seasons, seasons tweaks, epicloot, Plant Everything, and Odinship Plus. disabling all but seasons and BepInEx has had no effect on the previous experiments, exiting game sets timers to 11 days, logging out and back in removes and breaks the timer and mod. guess I gotta wait for an update or drop the mod.

![new world bugshot](https://github.com/RustyMods/Seasonality/assets/157019112/eaab8ad8-5e35-445f-a9ae-ccb13ca88bb2)

**Comment by RustyMods** [comment]
go to the bottom of the configs and reset data.

you might be copying over configs from a world that is older than your new one

**Comment by TheMythicSock** [comment]
That seems to have fixed it, the very last section on the config said default value was zero, so I changed it to zero and its now set to summer and has correct timer. I don't think I can stress this one enough, but THANK YOU, I adore this mod and the idea of it, its absolutely wonderful and makes the game feel so good.
