### ISSUE TITLE
Feature Suggestion - Make ice impassable to boats

### ISSUE THREAD

**Issue by frivolour** [RustyMods/Seasonality#18]
At the moment, if you enable the option for water to freeze in winter, boats are able to sail through said frozen water without issue.
This is not intuitive, breaks immersion, and gets rid of some interesting emergent scenarios (no getting your boat stranded in ice a la John Franklin). Imho it would be better if the ice was impassable to boats, though I have no idea how hard that is to implement.

**Comment by Karmacopper** [comment]
Plus one for this. Boats should be immovable if the sea is frozen.

**Comment by RustyMods** [comment]
i had the opposite recommendation when i first brought frozen water and did just that - so i won't be making ice impassable.
