### ISSUE TITLE
Feature Suggestion - Allow more modifiers per season

### ISSUE THREAD

**Issue by frivolour** [RustyMods/Seasonality#19]
At the moment we are only able to set one stat modifier and one resistance modifier per season  (unless I am simply failing to use the configs properly). It would be nice if we could set multiple of each per season, allowing us to gives pros and cons simultaneously (such as resistance to fire but weakness to frost in winter, etc...). 

This could perhaps take the form of a single dictionary config of the form `{modifier1: strength1, modifier2: strength2, ...}` rather than two separate configs for the type of modifier and then its degree.

Additionally it would be nice if we could set more permanent statuses (like the permanent cold in winter). Permanent wet in spring comes to mind, or perhaps permanent freezing in winter for a hardcore experience.

**Comment by RustyMods** [comment]
This is possible using yml config option. Please find a read me file in your configs alongside a few yml files to modify at your leisure
