### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Oosquai** [RustyMods/Seasonality#2]
Hi Rusty!  I'm not trying to nag here - I'm just not sure if the other thread notified you I left another message.  Feel free to close (or ask me to close) any of these.

I did some more testing on performance.  With only Seasonality installed, I get 40 fps.  With no mods installed, I get 100 fps.

I love this mod so much.  Are you also seeing performance issues?  Is there hope?  I'm building a private modded server for a dozen friends to play on, and I love this mod so much I'm subtitling the entire adventure, "Happy Little Accidents," inspired by you, and in honor of Bob Ross.  :)

But I can't inflict such a sharp performance drop on my friends.  Here's to hoping you have magical fixes on the way!  Thank you for this beautiful mod!

**Comment by RustyMods** [comment]
Have you tried changing your boot.config file ?

add these 2 lines at the top:

gfx-enable-gfx-jobs=1
gfx-enable-native-gfx-jobs=1

working on performance optimizations as well,

**Comment by Oosquai** [comment]
Thanks Rusty!  I'm the same person chatting about this with you on Odin+ Discord - Sav.  Sorry for the double-post.  This one here was before I found the Discord.  Feel free to close this ticket.  Thanks!
