### ISSUE TITLE
the seasons not changed 

### ISSUE THREAD

**Issue by sourcescaner** [RustyMods/Seasonality#3]
downloaded Seasonality with thunderstore mod manager and seasons dont change at all.
Only one season worked.
Enable 1 - Lock Configuratio ON did not help.

config do not working.

**Comment by RustyMods** [comment]
set control to on, to start changing seasons manually. else, use values.

timer is dependent on age of world to calculate seasons. looking to improve logic, works a bit weirdly since I want seasons to persist after log out

**Comment by sourcescaner** [comment]
No, I like when seasons changing automatically.
Now, when duration to more then 2 day in the game the current season stay as long as 4 hour.
This is abnormal value for the timer.
My world restarts very offen and timer very differ after restart the world.
Only duration in 1 day works good. The other values provide the timer to many hours (more then 4 hour) waiting to another season.
