### ISSUE TITLE
Invisible ocean waves during Winter with frozen water disabled

### ISSUE THREAD

**Issue by pjmichor** [RustyMods/Seasonality#32]
Been noticing invisible waves while sailing during the winter season. Weather is enabled, Always Cold enabled, but Frozen Water & Weather Freezes are both disabled. No changes to the Winter Weather Options. Water surfaces is unmoving, flat as it can be, but the waves still happen causing player, boat, fish, serpents to all float above and below the flat water plane.

I backed out, changed the season to spring, loaded into the world again, and within 20 seconds, the water surface was wavy and alive again. Perhaps the Frozen Water setting still affecting winter oceans despite being disabled?

**Comment by SaltSouls** [comment]
Yeah, I'm also noticing weird water behavior during winter.

**Comment by pjmichor** [comment]
> Yeah, I'm also noticing weird water behavior during winter.

I ended up removing the plugin and its config, reinstalling both fresh copies, then adjusted the stuff again and haven't seen the issue since. Give that a try?
