### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Iterny** [RustyMods/Seasonality#39]
Hello, how can i change language for mod? I've translated english file from github, but adding it in mod folder doesn't change anything. Is it supposed to be stored in config folder or in plugin folder? should i add some subfolders like Translation/[language]/and put file there? Also localization file should be in yml or json format?

**Comment by RustyMods** [comment]
JSON or YMl is fine. Needs to be in the config folder

**Comment by Iterny** [comment]
Something still not working, i validated yml file, everything seems to be alright. I put file in config folder but mod still doesn't use it. Sorry i'm newbie in modding, maybe doing something wrong
![image](https://github.com/user-attachments/assets/82b5c2c7-d6e3-4f2d-bbcb-cf00a01722e6)
i also put copy of file just in config folder next to Seasonality folder, but still no luck :(

**Comment by Iterny** [comment]
oh okay, me silly, i had to create Translation folder inside of Seasonality folder and now it works
