### ISSUE TITLE
Localization issues again

### ISSUE THREAD

**Issue by Iterny** [RustyMods/Seasonality#40]
Hello, it's me again. Sorry to bother, but odd thing happened, right after me closing topic, mod or game again decided to completely ignore translation. I tested both yml and json files, tried to put them everywhere in config folder, inside of seasonality folder, outside, made Translation subfolder inside Seasonality, nothing works. I'm really out of ideas what is wrong so maybe you kindly can just add localization with any next update of the mod? Or if you have any ideas why it's not working :(
[Russian.json](https://github.com/user-attachments/files/16970606/Russian.json)

**Comment by Iterny** [comment]
`season_spring: "Весна"
season_summer: "Лето"
season_fall: "Осень"
season_winter: "Зима"

season_spring_tooltip: "Весна пришла, природа оживает!"
season_summer_tooltip: "Лето настало, жара будет знойной!"
season_fall_tooltip: "Осень пришла, время собирать урожай!"
season_winter_tooltip: "Зима наступила, время утепляться!"

msg_spring: "Корабли отправляются в путь, в небесах птицы,\nНад матчами реют победные краски,\nВикинг, испей напоследок водицы,\nПылают сердца словно древние сказки."

msg_summer: "Огни на кострах, зовут за собою,\nМы пронесём его через жизни смятенье,\nПусть в битвах как в сказке, мы станем горою,\nВ пламени крови — их вечное бремя."

msg_fall: "Осень все зрит, унося за собой,\nЛистья златые, как щиты на ладонях.\nСланцы густых лесов копируют строй,\nВикинги мчатся вперед к победе на конях!"

msg_winter: "Звенит молот Тора, разрывая тьму,\nВ дни ярости, смелости, славы!\nНе страшны нам ни бури, ни боль, топор я покрепче сожму,\nС братьямя вместе не видим преграды!"

msg_ready: "Готов"

se_skill_modifier: "Множитель опыта"
se_damage: "Множитель урона"
## Weather Names
weather_clear: "Ясная погода"
weather_misty: "Туманно"
weather_darklands_dark: "Сумрак темных земель"
weather_heath_clear: "Ясная погода пустошь"
weather_gd_king: "Древний"
weather_lightrain: "Легкий дождь"
weather_thunderstorm: "Гроза"
weather_goblinking: "Яглут"
weather_nofogts: "Гроза без тумана"
weather_swamp_rain: "Болота дождь"
weather_bonemass: "Масса костей"
weather_twilight_clear: "Ясная погода сумерки"
weather_twilight_snow: "Снег сумерки"
weather_twilight_snowstorm: "Снежная буря сумерки"
weather_snowstorm: "Снежная буря"
weather_moder: "Моудер"
weather_ash_rain: "Пепельный дождь"
weather_sunken_crypts: "Затонувшие склепы"
weather_mistlands_clear: "Ясная погода туманные земли"
weather_mistlands_rain: "Дождь туманные земли"
weather_mistlands_thunder: "Гроза туманные земли"
weather_infected_mine: "Зараженный рудник"
weather_seeker_queen: "Королева"
weather_crypt: "Крипты"
weather_caves: "Пещеры"
weather_snow: "Снег"
weather_rain: "Дождь"
weather_ashlands_ashrain: "Пепельный дождь пепельные земли"
weather_ashlands_clear: "Ясная погода Хель"
weather_ashlands_seastorm: "Морской шторм Хель"
weather_ashlands_cinderrain: "Зольный дождь"
weather_deepforest_mist: "Лесной туман"
weather_warmsnow: "Снег теплый"
weather_warmsnowstorm: "Снежная буря теплая"
weather_nightfrost: "Ночной лес"
## Weather Tooltip
weather_clear_tooltip: "Погода стоит ясная и спокойная"
weather_misty_tooltip: "Боги не общаются с ясновидящими"
weather_darkland_dark_tooltip: "Настоящий воин никогда не боится темноты"
weather_heath clear_tooltip: "Погода ясная, но опасная"
weather_deep_forest_mist_tooltip: "Будьте осторожны в густом лесном тумане"
weather_gd_king_tooltip: "Древняя энергия леса вздымается в небо"
weather_rain_tooltip: "Отличный день для того, чтобы остаться дома"
weather_lightrain_tooltip: "Отличное время для охоты на никсов"
weather_thunderstorm_tooltip: "Боги разгневаны"
weather_eikthyr_tooltip: "Мощь Эйктюра чувствуется в воздухе"
weather_goblinking_tooltip: "Воздух заполнен энергией Проклятого Короля"
weather_nofogts_tooltip: "В эти дни дождь выглядит иначе"
weather_swamp_rain_tooltip: "Капельки дождя кислые на вкус"
weather_bonemass_tooltip: "Смрад болот буквально осязаем"
weather_snow_tooltip: "Воздух холодный и промозглый"
weather_twilight_clear_tooltip: "Затишье перед бурей"
weather_twilight_snow_tooltip: "Прекрасное проявляется во множестве форм"
weather_twilight_snowstorm_tooltip: "Ледяное небо холодное и пугающее"
weather_snowstorm_tooltip: "Настоящий викинг знает, как ориентироваться в самую суровую погоду"
weather_moder_tooltip: "Что-то могущественное парит в ледяных небесах"
weather_ash_rain_tooltip: "Даже Богиня Смерти не выдержит такой температуры"
weather_crypt_tooltip: "Мрачные времена требуют умеренных мер"
weather_sunken_crypt_tooltip: "Звук водосточных труб разносится по всей округе"
weather_caves_tooltip: "Неглубокие недра гор взывают к тебе"
weather_mistlands_clear_tooltip: "Погода проясняется, но страх никуда не ушел"
weather_mistlands_rain_tooltip: "Боги взывают к твоему приходу"
weather_mistlands_thunder_tooltip: "Небо распахивается, открывая волшебные мгновения"
weather_infected_mine_tooltip: "Время для беспокойства давно прошло"
weather_queen_tooltip: "Пришло время проявить свою храбрость"
weather_ashlands_ashrain_tooltip: ""
weather_ashlands_clear_tooltip: ""
weather_ashlands_seastorm_tooltip: ""
weather_ashlands_cinderrain_tooltip: ""
weather_deepforest_mist_tooltip: ""
weather_warmsnow_tooltip: ""
weather_warmsnowstorm_tooltip: ""
weather_nightfrost_tooltip: ""`

yml option, couldn't add file, github forbid

**Comment by RustyMods** [comment]
Seasonality.Russian.json
Seasonality.Russian.yml

add it directly to the config folder instead maybe.

BepinEx/Config

**Comment by Iterny** [comment]
Woohoo! renaming helped, thank you! I hope it's last time this issue occur. It's strange because I don't touch anything last time, it worked on its own for once, but then it stopped. Thank you for quick response. Great mod, not so complicated and adds tons of immersivity. Up to you adding localization that i've sent, tried to translate those rhymes to keep meaning and rhyme together, but i'm not poet >_<

thanks for help again
