### ISSUE TITLE
A request actually

### ISSUE THREAD

**Issue by MidaZ17** [RustyMods/Seasonality#9]
Hey Rusty, tried to join and contact you trough Odin discord, but every invite seems to be expired.
I was wondering if you could add kinda of a random start/end timer for the weather effects. As it seems for now, it is always starting at the very beginning of seasons that has effects and last for (X) minutes. 
Is there a way to make it start at a random time in the season and last for a 0-100% season time?

Thanks dude, btw, great fucking work! Love this mod.

**Comment by Lord-Kamina** [comment]
Yeah it'd be cool for weather to have variable durations between a range.

**Comment by RustyMods** [comment]
> Hey Rusty, tried to join and contact you trough Odin discord, but every invite seems to be expired. I was wondering if you could add kinda of a random start/end timer for the weather effects. As it seems for now, it is always starting at the very beginning of seasons that has effects and last for (X) minutes. Is there a way to make it start at a random time in the season and last for a 0-100% season time?
> 
> Thanks dude, btw, great fucking work! Love this mod.

Thank you, 
I cannot make this request possible, would require to create a whole new status effect system.

**Comment by RustyMods** [comment]
> Yeah it'd be cool for weather to have variable durations between a range.

Next update, i'm adding in depth yaml configurations,
- custom weather creation
- unlimited weather choice

You will be able to create a version of this request, by adding the same weather multiple  times
